# -*- coding: utf-8 -*-
"""Copia de Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HC1E2Tejd5xPkkclVVOU_QGZiub668iR

# Two-Level Genetic Algorithm for AutoML NAS
## Nuevo Colab — Búsqueda arquitectural con GA en dos niveles

**Contribución central:** comparar GA vs BO para la calibración del vector de
pesos de una combinación lineal de Zero-Cost Proxies, y usar el proxy
calibrado por GA para búsqueda arquitectural dentro y fuera de NATS-Bench TSS.

### Pipeline completo
1. Cargar ground truth y ZCPs del Colab anterior
2. Expandir ZCPs a las 15.625 arquitecturas completas
3. GA Nivel 1: calibrar vector de pesos del proxy (comparar vs BO y RS)
4. GA Nivel 2: búsqueda arquitectural dentro del benchmark
5. NSGA-II: búsqueda multi-objetivo (accuracy vs eficiencia)
6. Espacio extendido: buscar fuera del benchmark
7. Entrenamiento y validación real de las mejores candidatas

## Bloque 1 — Setup
"""

import os, bz2, pickle
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from scipy import stats
from concurrent.futures import ThreadPoolExecutor, as_completed
try:
    from tqdm.auto import tqdm
except ImportError:
    from tqdm import tqdm

# ── Rutas ────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR   = os.path.join(SCRIPT_DIR, 'CSV')
NATS_PATH  = os.path.join(BASE_DIR, 'NATS-tss-v1_0-3ffb9-simple', 'NATS-tss-v1_0-3ffb9-simple')
CSV_GT     = os.path.join(BASE_DIR, 'nats_ground_truth.csv')
CSV_ZCP    = os.path.join(BASE_DIR, 'nats_zcps.csv')
CSV_ZCP_FULL = os.path.join(BASE_DIR, 'nats_zcps_full.csv')
CIFAR_DIR  = os.path.join(SCRIPT_DIR, 'tmp', 'cifar10')

DATASET, SEED, BUDGET = 'cifar10-valid', 777, '200'
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'✓ Device : {DEVICE}')

# ── Cargar ground truth ───────────────────────────────────────
assert os.path.exists(CSV_GT), f'❌ No encontrado: {CSV_GT}'
df = pd.read_csv(CSV_GT)
df['rank_real'] = df['acc_valid'].rank(ascending=False, method='min').astype(int)
print(f'✓ Ground truth: {len(df)} arquitecturas')
print(f'  acc_valid: {df.acc_valid.min():.2f}% — {df.acc_valid.max():.2f}%')

"""## Bloque 2 — Red PyTorch y funciones ZCP

Misma implementación del Colab anterior. Necesaria para computar ZCPs
sobre las arquitecturas restantes.
"""

# ── Constructor de redes ──────────────────────────────────────
class ReLUConvBN(nn.Module):
    def __init__(self, C, kernel, stride, pad):
        super().__init__()
        self.op = nn.Sequential(
            nn.ReLU(inplace=False),
            nn.Conv2d(C, C, kernel, stride=stride, padding=pad, bias=False),
            nn.BatchNorm2d(C, affine=True),
        )
    def forward(self, x): return self.op(x)

class Zero(nn.Module):
    def __init__(self, stride):
        super().__init__()
        self.stride = stride
    def forward(self, x):
        if self.stride == 1: return x.mul(0.)
        return x[:, :, ::self.stride, ::self.stride].mul(0.)

class FactorizedReduce(nn.Module):
    def __init__(self, C):
        super().__init__()
        self.relu  = nn.ReLU(inplace=False)
        self.conv1 = nn.Conv2d(C, C//2, 1, stride=2, padding=0, bias=False)
        self.conv2 = nn.Conv2d(C, C//2, 1, stride=2, padding=0, bias=False)
        self.bn    = nn.BatchNorm2d(C, affine=True)
    def forward(self, x):
        x = self.relu(x)
        return self.bn(torch.cat([self.conv1(x),
                                  self.conv2(x[:,:,1:,1:])], dim=1))

def make_op(op_name, C, stride):
    if op_name == 'none'         : return Zero(stride)
    if op_name == 'skip_connect' : return nn.Identity() if stride==1 else FactorizedReduce(C)
    if op_name == 'nor_conv_1x1' : return ReLUConvBN(C, 1, stride, 0)
    if op_name == 'nor_conv_3x3' : return ReLUConvBN(C, 3, stride, 1)
    if op_name == 'avg_pool_3x3' : return nn.AvgPool2d(3, stride=stride,
                                                        padding=1,
                                                        count_include_pad=False)
    raise ValueError(f'Op desconocida: {op_name}')

class NATSCell(nn.Module):
    def __init__(self, arch_str, C, stride):
        super().__init__()
        self.ops, self.edges = nn.ModuleList(), []
        for dst, block in enumerate(arch_str.split('+'), start=1):
            for part in [p for p in block.split('|') if p.strip()]:
                op_name, src = part.strip().split('~')
                src = int(src)
                self.ops.append(make_op(op_name, C, stride if src==0 else 1))
                self.edges.append((src, dst))
    def forward(self, x):
        nodes = [x]
        for dst in range(1, 4):
            inputs = [self.ops[i](nodes[src])
                      for i,(src,d) in enumerate(self.edges) if d==dst]
            nodes.append(sum(inputs))
        return nodes[-1]

class TinyNetwork(nn.Module):
    def __init__(self, arch_str, n_classes=10, C=16):
        super().__init__()
        self.stem       = nn.Sequential(nn.Conv2d(3,C,3,padding=1,bias=False),
                                        nn.BatchNorm2d(C))
        self.cells      = nn.ModuleList([NATSCell(arch_str,C,s)
                                         for s in [1,2,1,2,1]])
        self.lastact    = nn.Sequential(nn.BatchNorm2d(C), nn.ReLU(inplace=False))
        self.gap        = nn.AdaptiveAvgPool2d(1)
        self.classifier = nn.Linear(C, n_classes)
    def forward(self, x):
        x = self.stem(x)
        for cell in self.cells: x = cell(x)
        x = self.lastact(x)
        x = self.gap(x).view(x.size(0), -1)
        return self.classifier(x), None

def build_network(arch_str, n_classes=10, C=16):
    return TinyNetwork(arch_str, n_classes=n_classes, C=C)

# ── Mini-batch CIFAR-10 ───────────────────────────────────────
import torchvision, torchvision.transforms as T

transform   = T.Compose([T.ToTensor(),
                          T.Normalize((0.4914,0.4822,0.4465),
                                      (0.2470,0.2435,0.2616))])
cifar_train = torchvision.datasets.CIFAR10(CIFAR_DIR, train=True,
                                            download=True, transform=transform)
loader      = torch.utils.data.DataLoader(cifar_train, batch_size=64,
                                           shuffle=True, num_workers=0)
x_batch, y_batch = next(iter(loader))
x_batch = x_batch.to(DEVICE)
y_batch = y_batch.to(DEVICE)
criterion = nn.CrossEntropyLoss()
print(f'✓ CIFAR-10 batch: {tuple(x_batch.shape)}')

# ── Funciones ZCP ─────────────────────────────────────────────
def zcp_grad_norm(net, x, y):
    net.zero_grad()
    criterion(net(x)[0], y).backward()
    return sum(p.grad.norm().item()**2
               for p in net.parameters() if p.grad is not None)**0.5

def zcp_snip(net, x, y):
    net.zero_grad()
    criterion(net(x)[0], y).backward()
    return sum((p.grad*p.data).abs().sum().item()
               for p in net.parameters() if p.grad is not None)

def zcp_grasp(net, x, y, T=1):
    net.zero_grad()
    criterion(net(x)[0]/T, y).backward(retain_graph=True)
    g1 = {n: p.grad.clone() for n,p in net.named_parameters() if p.grad is not None}
    net.zero_grad()
    criterion(net(x)[0]/T, y).backward()
    return sum(-(g1[n]*p.grad*p.data).sum().item()
               for n,p in net.named_parameters()
               if p.grad is not None and n in g1)

def zcp_jacob_cov(net, x):
    net.zero_grad()
    x_in = x.clone().detach().requires_grad_(True)
    net(x_in)[0].backward(torch.ones(x.shape[0],10).to(x.device))
    J    = x_in.grad.detach().reshape(x.shape[0],-1).cpu().numpy()
    eigv = np.abs(np.linalg.eigvalsh(J @ J.T))
    return float(np.log(eigv+1e-5).sum())

def zcp_synflow(net, x):
    ones   = torch.ones_like(x)
    signs  = [p.data.sign().clone() for p in net.parameters()]
    for p in net.parameters(): p.data.abs_()
    net.zero_grad()
    net(ones)[0].sum().backward()
    score = sum((p.data*p.grad).sum().item()
                for p in net.parameters() if p.grad is not None)
    for p,s in zip(net.parameters(), signs): p.data.mul_(s)
    return score

def compute_all_zcps(arch_str, x, y, C=16):
    try:
        net = build_network(arch_str, C=C).to(DEVICE).train()
        torch.manual_seed(hash(arch_str) % (2**31))
        for p in net.parameters():
            if p.dim() > 1: nn.init.kaiming_normal_(p)
        return {
            'grad_norm' : zcp_grad_norm(net, x, y),
            'snip'      : zcp_snip(net, x, y),
            'grasp'     : zcp_grasp(net, x, y),
            'jacob_cov' : zcp_jacob_cov(net, x),
            'synflow'   : zcp_synflow(net, x),
        }
    except Exception:
        return None

print('✓ Funciones ZCP y red definidas')

"""## Bloque 3 — Expansión de ZCPs a las 15.625 arquitecturas completas

Pre-computamos ZCPs para TODAS las arquitecturas del benchmark.
Esto elimina el problema de extrapolación del proxy fuera del dominio calibrado.
El GA Nivel 2 tendrá fitness confiable en todo el espacio de búsqueda.

**Tiempo estimado:** ~25 min en GPU. Se cachea en CSV — nunca se repite.
"""

ZCP_COLS = ['grad_norm', 'snip', 'grasp', 'jacob_cov', 'synflow']

if os.path.exists(CSV_ZCP_FULL):
    df_zcp_full = pd.read_csv(CSV_ZCP_FULL)
    print(f'✓ ZCPs completos cargados: {len(df_zcp_full)} arquitecturas')
else:
    # Verificar cuáles ya están computados (del Colab anterior)
    already_done = set()
    if os.path.exists(CSV_ZCP):
        df_prev = pd.read_csv(CSV_ZCP)
        already_done = set(df_prev['arch_id'].tolist())
        print(f'  ZCPs previos encontrados: {len(already_done)} arquitecturas')

    pending = [i for i in range(15625) if i not in already_done]
    print(f'  Arquitecturas pendientes: {len(pending)}')
    print(f'  Computando ZCPs con GPU...')

    new_rows = []
    for arch_id in tqdm(pending):
        astr = df.loc[df['arch_id']==arch_id, 'arch_str'].values[0]
        res  = compute_all_zcps(astr, x_batch, y_batch)
        if res:
            res['arch_id'] = arch_id
            new_rows.append(res)

    # Combinar previos + nuevos
    df_new = pd.DataFrame(new_rows)
    if os.path.exists(CSV_ZCP):
        df_zcp_full = pd.concat([df_prev, df_new], ignore_index=True)
    else:
        df_zcp_full = df_new

    df_zcp_full = df_zcp_full.sort_values('arch_id').reset_index(drop=True)
    df_zcp_full.to_csv(CSV_ZCP_FULL, index=False)
    print(f'✓ CSV completo guardado: {len(df_zcp_full)} arquitecturas')

# ── Unir con ground truth ─────────────────────────────────────
df_full = df_zcp_full.merge(
    df[['arch_id','arch_str','acc_valid','params_k','rank_real']],
    on='arch_id'
)
print(f'✓ Dataset completo: {len(df_full)} arquitecturas × {df_full.shape[1]} columnas')
print(f'\n  Verificación ZCPs:')
for col in ZCP_COLS:
    print(f'  {col:12s}: [{df_full[col].min():.3f}, {df_full[col].max():.3f}]')

"""## Bloque 4 — Normalización y conjunto de calibración

Normalizamos los ZCPs al rango [0,1] usando el dataset completo (15.625 arqs).
Esto garantiza que la normalización cubre todo el espacio de búsqueda.

Separamos el dataset en:
- **Calibración (1.001 arqs):** las mismas del Colab anterior → comparabilidad con BO
- **Validación (14.624 arqs):** para evaluar generalización del proxy calibrado
"""

import os

# ── Crear carpeta de salidas ──────────────────────────────────
SALIDAS = os.path.join(SCRIPT_DIR, 'Salidas')
os.makedirs(SALIDAS, exist_ok=True)
print(f'✓ Carpeta de salidas: {SALIDAS}')

ZCP_COLS  = ['grad_norm', 'snip', 'grasp', 'jacob_cov', 'synflow', 'params_k']

# ── Agregar params_k al dataset de ZCPs ───────────────────────
df_full = df_full.merge(df[['arch_id','params_k']], on='arch_id', how='left',
                         suffixes=('','_dup'))
if 'params_k_dup' in df_full.columns:
    df_full.drop(columns=['params_k_dup'], inplace=True)

# ── Normalización min-max sobre el dataset COMPLETO ───────────
# Signo: positivo si Spearman(proxy, acc_valid) > 0, negativo si < 0
norm_params = {}
df_norm = df_full.copy()

print('─── Normalización (signo y rango) ───────────────────────')
for col in ZCP_COLS:
    r, _ = stats.spearmanr(df_full[col], df_full['acc_valid'])
    sign  = 1 if r >= 0 else -1
    vals  = df_full[col] * sign
    vmin, vmax = vals.min(), vals.max()
    norm_params[col] = {'sign': sign, 'min': vmin, 'max': vmax}
    df_norm[f'{col}_norm'] = (vals - vmin) / (vmax - vmin + 1e-8)
    print(f'  {col:12s}: ρ={r:+.4f}  signo={sign:+d}  '
          f'rango norm=[{df_norm[f"{col}_norm"].min():.3f},'
          f'{df_norm[f"{col}_norm"].max():.3f}]')

NORM_COLS = [f'{c}_norm' for c in ZCP_COLS]

# ── Conjunto de calibración: mismas 1001 arqs del Colab anterior ──
df_calib = pd.read_csv(CSV_ZCP)[['arch_id']].merge(df_norm, on='arch_id')
df_val   = df_norm[~df_norm['arch_id'].isin(df_calib['arch_id'])].copy()

print(f'\n✓ Calibración : {len(df_calib)} arquitecturas')
print(f'  Validación  : {len(df_val)} arquitecturas')
print(f'  Total       : {len(df_norm)} arquitecturas')

# ── Función Precision@K (usada como fitness del GA Nivel 1) ───
def precision_at_k(weights: dict, df_eval: pd.DataFrame,
                   k: int = 50) -> float:
    score    = sum(weights[col] * df_eval[f'{col}_norm']
                   for col in ZCP_COLS)
    rank_proxy = score.rank(ascending=False, method='min')
    top_real   = set(df_eval.nsmallest(k, 'rank_real')['arch_id'])
    top_proxy  = set(df_eval[rank_proxy <= k]['arch_id'])
    return len(top_real & top_proxy) / k

# ── Líneas base sobre el conjunto de calibración ──────────────
print('\n─── Líneas base Precision@50 (calibración) ─────────────')
for col in ZCP_COLS:
    w = {c: (1.0 if c==col else 0.0) for c in ZCP_COLS}
    p = precision_at_k(w, df_calib, k=50)
    print(f'  {col:12s}: {p:.4f}')

w_eq = {c: 1.0 for c in ZCP_COLS}
print(f'  {"igual":12s}: {precision_at_k(w_eq, df_calib, k=50):.4f}')

"""## Bloque 5 — GA Nivel 1: optimización del vector de pesos del proxy

El GA busca el vector w ∈ [-1,1]⁶ que maximiza Precision@50 sobre la
calibración. Cada individuo es un vector de 6 reales (uno por ZCP).

**Operadores para espacio continuo:**
- Cruce: BLX-α (Blend Crossover) — genera hijos en el intervalo extendido entre padres
- Mutación: gaussiana con σ adaptativo
- Selección: torneo de tamaño 3
- Elitismo: top-3 pasan sin modificación

**Comparación justa con BO:**
- Mismo conjunto de calibración (1001 arqs)
- Mismo presupuesto: 100 evaluaciones de Precision@50
- 10 corridas independientes para medir estabilidad
"""

import random
import time

# ── GA Nivel 1: pesos continuos ───────────────────────────────
N_WEIGHTS = len(ZCP_COLS)
W_MIN, W_MAX = -1.0, 1.0

def random_weights():
    return [random.uniform(W_MIN, W_MAX) for _ in range(N_WEIGHTS)]

def weights_to_dict(w):
    return {col: w[i] for i, col in enumerate(ZCP_COLS)}

def fitness_weights(w, df_eval=None, k=50):
    if df_eval is None: df_eval = df_calib
    return precision_at_k(weights_to_dict(w), df_eval, k=k)

def blx_crossover(p1, p2, alpha=0.3):
    """BLX-α: hijo en intervalo [min-α*d, max+α*d]"""
    child = []
    for a, b in zip(p1, p2):
        lo, hi = min(a,b), max(a,b)
        d = hi - lo
        lo_ext = max(W_MIN, lo - alpha*d)
        hi_ext = min(W_MAX, hi + alpha*d)
        child.append(random.uniform(lo_ext, hi_ext))
    return child

def mutate_gaussian(ind, sigma=0.15):
    return [max(W_MIN, min(W_MAX, g + random.gauss(0, sigma)))
            for g in ind]

def tournament(pop, fits, k=3):
    idx = random.sample(range(len(pop)), k)
    return pop[max(idx, key=lambda i: fits[i])][:]

def run_ga_level1(pop_size=20, n_gen=5, p_cross=0.8,
                  p_mut=0.3, elite_k=2, sigma=0.15,
                  k_precision=50, seed=42):
    """
    GA para optimizar vector de pesos del proxy.
    Presupuesto total ≈ pop_size + (pop_size * n_gen) evaluaciones.
    Con pop_size=20, n_gen=5 → 100 evaluaciones (igual que BO).
    """
    random.seed(seed)
    pop  = [random_weights() for _ in range(pop_size)]
    fits = [fitness_weights(ind, k=k_precision) for ind in pop]
    history = [max(fits)]

    for gen in range(n_gen):
        sorted_idx = sorted(range(len(pop)), key=lambda i: fits[i], reverse=True)
        new_pop    = [pop[i][:] for i in sorted_idx[:elite_k]]

        while len(new_pop) < pop_size:
            p1 = tournament(pop, fits)
            p2 = tournament(pop, fits)
            child = blx_crossover(p1, p2) if random.random() < p_cross \
                    else p1[:]
            if random.random() < p_mut:
                child = mutate_gaussian(child, sigma)
            new_pop.append(child)

        pop  = new_pop
        fits = [fitness_weights(ind, k=k_precision) for ind in pop]
        history.append(max(fits))

    best_idx = max(range(len(pop)), key=lambda i: fits[i])
    return pop[best_idx], fits[best_idx], history

# ── 10 corridas independientes ────────────────────────────────
print('Ejecutando GA Nivel 1 — 10 corridas independientes...')
print(f'  Configuración: pop=20, gen=5, total≈100 eval. por corrida\n')

N_RUNS  = 10
results_ga1 = []
t0 = time.time()

for run in range(N_RUNS):
    best_w, best_p, hist = run_ga_level1(
        pop_size=20, n_gen=5, seed=run*17
    )
    results_ga1.append({
        'run': run, 'best_p50': best_p,
        'weights': best_w, 'history': hist
    })
    print(f'  Run {run+1:2d}: Precision@50 = {best_p:.4f}')

elapsed = time.time() - t0
print(f'\n✓ GA Nivel 1 completado en {elapsed:.1f}s')
print(f'  P@50 media  : {np.mean([r["best_p50"] for r in results_ga1]):.4f}')
print(f'  P@50 std    : {np.std([r["best_p50"]  for r in results_ga1]):.4f}')
print(f'  P@50 mejor  : {max(r["best_p50"]      for r in results_ga1):.4f}')
print(f'  P@50 peor   : {min(r["best_p50"]      for r in results_ga1):.4f}')

# Mejor solución global
best_run = max(results_ga1, key=lambda r: r['best_p50'])
best_weights_ga = weights_to_dict(best_run['weights'])

print(f'\n─── Pesos óptimos del GA ─────────────────────────────')
for col, w in best_weights_ga.items():
    bar = '█' * int(abs(w)*20)
    print(f'  {col:12s}: {w:+.4f}  {"+" if w>=0 else "-"}{bar}')

"""### Comparación GA vs BO vs RS — mismo presupuesto (100 evaluaciones)"""

# ── Random Search para pesos (100 evaluaciones) ───────────────
print('Ejecutando RS para pesos — 10 corridas...\n')
results_rs1 = []

for run in range(N_RUNS):
    random.seed(run*31 + 100)
    candidates = [random_weights() for _ in range(100)]
    fits_rs    = [fitness_weights(c, k=50) for c in candidates]
    best_idx   = np.argmax(fits_rs)
    results_rs1.append({
        'run': run,
        'best_p50': fits_rs[best_idx],
        'weights': candidates[best_idx]
    })
    print(f'  Run {run+1:2d}: Precision@50 = {fits_rs[best_idx]:.4f}')

# ── Resultado BO del Colab anterior (referencia) ─────────────
bo_p50   = 0.68   # obtenido en Colab anterior
bo_weights = {
    'grad_norm' : -1.0000,
    'snip'      : +0.6531,
    'grasp'     : -0.5493,
    'jacob_cov' : +0.6881,
    'synflow'   : -0.1471,
    'params_k'  : +0.3871,
}

# ── Tabla comparativa ─────────────────────────────────────────
ga_p50s = [r['best_p50'] for r in results_ga1]
rs_p50s = [r['best_p50'] for r in results_rs1]

print('\n' + '═'*55)
print('COMPARACIÓN: GA vs BO vs RS para calibración de pesos')
print('═'*55)
print(f'  {"Método":12s}  {"Media":>8}  {"Std":>8}  '
      f'{"Mejor":>8}  {"Peor":>8}')
print('  ' + '─'*47)
print(f'  {"GA (10 runs)":12s}  {np.mean(ga_p50s):>8.4f}  '
      f'{np.std(ga_p50s):>8.4f}  {max(ga_p50s):>8.4f}  '
      f'{min(ga_p50s):>8.4f}')
print(f'  {"RS (10 runs)":12s}  {np.mean(rs_p50s):>8.4f}  '
      f'{np.std(rs_p50s):>8.4f}  {max(rs_p50s):>8.4f}  '
      f'{min(rs_p50s):>8.4f}')
print(f'  {"BO (1 run)":12s}  {bo_p50:>8.4f}  '
      f'{"N/A":>8}  {bo_p50:>8.4f}  {"N/A":>8}')
print('═'*55)

# ── Gráfico ───────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Boxplot comparativo
axes[0].boxplot([ga_p50s, rs_p50s],
                tick_labels=['GA', 'RS'],
                patch_artist=True,
                boxprops=dict(facecolor='steelblue', alpha=0.7))
axes[0].axhline(bo_p50, color='red', linestyle='--',
                linewidth=2, label=f'BO = {bo_p50:.4f}')
axes[0].set_ylabel('Precision@50')
axes[0].set_title('Precision@50: GA vs RS vs BO\n(calibración de pesos, 100 eval.)')
axes[0].legend()
axes[0].set_ylim(0, 1)

# Convergencia promedio del GA
all_hists = np.array([r['history'] for r in results_ga1])
mean_hist = all_hists.mean(axis=0)
std_hist  = all_hists.std(axis=0)
gens      = range(len(mean_hist))

axes[1].plot(gens, mean_hist, 'o-', color='steelblue',
             linewidth=2, label='GA (media)')
axes[1].fill_between(gens,
                     mean_hist - std_hist,
                     mean_hist + std_hist,
                     alpha=0.2, color='steelblue')
axes[1].axhline(bo_p50, color='red', linestyle='--',
                label=f'BO = {bo_p50:.4f}')
axes[1].axhline(np.mean(rs_p50s), color='gray', linestyle=':',
                label=f'RS media = {np.mean(rs_p50s):.4f}')
axes[1].set_xlabel('Generación')
axes[1].set_ylabel('Precision@50')
axes[1].set_title('Convergencia GA Nivel 1\n(media ± std de 10 corridas)')
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig(f'{SALIDAS}/ga_nivel1_comparacion.png', dpi=120, bbox_inches='tight')
plt.show()

"""## Bloque 6 — GA Nivel 2: búsqueda arquitectural con proxy calibrado

Usamos los pesos óptimos encontrados por el GA Nivel 1 para construir el
proxy combinado. Luego el GA Nivel 2 busca la mejor arquitectura.

**Diferencia crítica respecto al Colab anterior:**
- Antes: GA generaba arquitecturas y computaba ZCPs on-the-fly → extrapolación
- Ahora: ZCPs pre-computados para las 15.625 arqs → proxy confiable en todo el espacio

El fitness de cada individuo se obtiene por lookup en la tabla pre-computada.
Comparamos GA vs Greedy vs RS con el mismo presupuesto de evaluaciones del proxy.
"""

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

OPS_LIST = ['none','skip_connect','nor_conv_1x1','nor_conv_3x3','avg_pool_3x3']
N_EDGES  = 6

# ── Construir proxy combinado con pesos del GA Nivel 1 ────────
def build_proxy(weights: dict, df_eval: pd.DataFrame) -> pd.Series:
    return sum(weights[col] * df_eval[f'{col}_norm'] for col in ZCP_COLS)

# ── Agregar columnas normalizadas a df_full ───────────────────
for col in ZCP_COLS:
    sign = norm_params[col]['sign']
    vmin = norm_params[col]['min']
    vmax = norm_params[col]['max']
    vals = df_full[col] * sign
    df_full[f'{col}_norm'] = (vals - vmin) / (vmax - vmin + 1e-8)

print('✓ Columnas normalizadas agregadas a df_full')
print(f'  Columnas: {[c for c in df_full.columns if c.endswith("_norm")]}')

# Verificar rango
for col in ZCP_COLS:
    v = df_full[f'{col}_norm']
    print(f'  {col}_norm: [{v.min():.3f}, {v.max():.3f}]')

# Proxy con mejores pesos del GA Nivel 1
df_full['proxy_ga'] = build_proxy(best_weights_ga, df_full)

# También con pesos del BO (para comparación)
bo_weights = {
    'grad_norm' : -1.0000, 'snip'     : +0.6531,
    'grasp'     : -0.5493, 'jacob_cov': +0.6881,
    'synflow'   : -0.1471, 'params_k' : +0.3871,
}
df_full['proxy_bo'] = build_proxy(bo_weights, df_full)

print('─── Correlación de proxies vs acc_valid ─────────────────')
for col in ['proxy_ga', 'proxy_bo']:
    r, _ = stats.spearmanr(df_full[col], df_full['acc_valid'])
    print(f'  {col:12s}: Spearman ρ = {r:+.4f}')

# ── Tabla de lookup: arch_str → (proxy_score, rank_real) ─────
proxy_lookup = df_full.set_index('arch_str')[['proxy_ga','rank_real',
                                               'acc_valid','params_k']].to_dict('index')

def genes_to_arch_str(genes):
    ops = [OPS_LIST[g] for g in genes]
    return (f'|{ops[0]}~0|+|{ops[1]}~0|{ops[2]}~1|'
            f'+|{ops[3]}~0|{ops[4]}~1|{ops[5]}~2|')

def get_proxy_score(genes):
    astr = genes_to_arch_str(genes)
    return proxy_lookup.get(astr, {}).get('proxy_ga', -np.inf)

# ── Operadores genéticos (discretos) ─────────────────────────
def random_ind():
    return [random.randint(0,4) for _ in range(N_EDGES)]

def tournament(pop, fits, k=3):
    idx = random.sample(range(len(pop)), k)
    return pop[max(idx, key=lambda i: fits[i])][:]

def one_point_crossover(p1, p2):
    pt = random.randint(1, N_EDGES-1)
    return p1[:pt]+p2[pt:], p2[:pt]+p1[pt:]

def mutate(ind, p_mut=0.2):
    return [random.randint(0,4) if random.random()<p_mut else g for g in ind]

# ── GA Nivel 2 ────────────────────────────────────────────────
def run_ga_level2(pop_size=50, n_gen=30, p_mut=0.2,
                  p_cross=0.8, elite_k=3, seed=42):
    random.seed(seed)
    pop  = [random_ind() for _ in range(pop_size)]
    fits = [get_proxy_score(ind) for ind in pop]
    cache = {tuple(ind): f for ind, f in zip(pop, fits)}

    history = []
    n_evals = pop_size

    for gen in range(n_gen):
        best_f = max(fits)
        best_i = np.argmax(fits)
        astr   = genes_to_arch_str(pop[best_i])
        info   = proxy_lookup.get(astr, {})
        history.append({
            'gen'      : gen,
            'best_fit' : best_f,
            'mean_fit' : np.mean(fits),
            'n_evals'  : n_evals,
            'rank_real': info.get('rank_real', np.nan),
            'acc_valid': info.get('acc_valid', np.nan),
        })

        sorted_idx = np.argsort(fits)[::-1]
        new_pop    = [pop[i][:] for i in sorted_idx[:elite_k]]

        while len(new_pop) < pop_size:
            p1 = tournament(pop, fits)
            p2 = tournament(pop, fits)
            c1, c2 = one_point_crossover(p1, p2) \
                     if random.random()<p_cross else (p1[:], p2[:])
            new_pop.append(mutate(c1, p_mut))
            if len(new_pop) < pop_size:
                new_pop.append(mutate(c2, p_mut))

        pop = new_pop
        new_fits = []
        for ind in pop:
            k = tuple(ind)
            if k not in cache:
                cache[k] = get_proxy_score(ind)
                n_evals += 1
            new_fits.append(cache[k])
        fits = new_fits

    # Mejor final
    best_idx  = np.argmax(fits)
    best_astr = genes_to_arch_str(pop[best_idx])
    best_info = proxy_lookup.get(best_astr, {})
    return pop[best_idx], fits[best_idx], history, best_info, n_evals

# ── Random Search Nivel 2 ─────────────────────────────────────
def run_rs_level2(n_evals=1500, seed=42):
    random.seed(seed)
    best_f, best_info = -np.inf, {}
    history = []
    for i in range(n_evals):
        ind  = random_ind()
        f    = get_proxy_score(ind)
        if f > best_f:
            best_f    = f
            astr      = genes_to_arch_str(ind)
            best_info = proxy_lookup.get(astr, {})
        if (i+1) % 50 == 0:
            history.append({'n_evals': i+1, 'best_fit': best_f,
                            'rank_real': best_info.get('rank_real', np.nan),
                            'acc_valid': best_info.get('acc_valid', np.nan)})
    return best_f, best_info, history

# ── Greedy search (baseline óptimo dentro del proxy) ─────────
def greedy_search(k_consult: int) -> dict:
    """
    Toma las top-k arquitecturas según proxy_ga y
    devuelve la mejor según acc_valid real.
    """
    top_k = df_full.nlargest(k_consult, 'proxy_ga')
    best  = top_k.loc[top_k['acc_valid'].idxmax()]
    return {'acc_valid': best['acc_valid'],
            'rank_real': int(best['rank_real']),
            'params_k' : best['params_k'],
            'arch_str' : best['arch_str']}

# ── Ejecutar todos los métodos ────────────────────────────────
print('Ejecutando GA Nivel 2 (3 corridas)...')
results_ga2 = []
for seed in [42, 7, 99]:
    _, best_f, hist, best_info, n_ev = run_ga_level2(
        pop_size=50, n_gen=30, seed=seed)
    results_ga2.append({'seed': seed, 'history': hist,
                        'best_info': best_info, 'n_evals': n_ev})
    print(f'  seed={seed}: acc={best_info.get("acc_valid","?"):.4f}%  '
          f'rank={int(best_info.get("rank_real","?"))}  '
          f'evals={n_ev}')

print('\nEjecutando RS Nivel 2...')
rs_f, rs_info, rs_hist = run_rs_level2(n_evals=1500, seed=42)
print(f'  RS: acc={rs_info.get("acc_valid","?"):.4f}%  '\
      f'rank={int(rs_info.get("rank_real","?"))}')

print('\nGreedy search (con pesos GA Nivel 1):')
for k in [10, 20, 50, 100]:
    g = greedy_search(k)
    print(f'  K={k:4d}: acc={g["acc_valid"]:.4f}%  '\
          f'rank={g["rank_real"]}  params={g["params_k"]:.1f}K')

"""### Visualización comparativa y tabla de resultados"""

# ── Tabla resumen ─────────────────────────────────────────────
print('\n' + '═'*65)
print('COMPARACIÓN GA NIVEL 2 vs RS vs GREEDY')
print('═'*65)
print(f'  {"Método":20s}  {"acc_valid":>10}  {"rank_real":>10}  {"evals":>8}')
print('  ' + '─'*52)

for r in results_ga2:
    info = r['best_info']
    print(f'  {"GA (seed="+str(r["seed"])+")":20s}  '
          f'{info.get("acc_valid",0):>10.4f}%  '
          f'{int(info.get("rank_real",0)):>10}  '
          f'{r["n_evals"]:>8}')

print(f'  {"RS (1500 evals)":20s}  '
      f'{rs_info.get("acc_valid",0):>10.4f}%  '
      f'{int(rs_info.get("rank_real",0)):>10}  '
      f'{"1500":>8}')

for k in [10, 20, 50]:
    g = greedy_search(k)
    print(f'  {"Greedy K="+str(k):20s}  '
          f'{g["acc_valid"]:>10.4f}%  '
          f'{g["rank_real"]:>10}  '
          f'{k:>8}')

print('═'*65)

# ── Gráfico convergencia ──────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

colors = ['steelblue','darkorange','green']
for i, r in enumerate(results_ga2):
    hist = pd.DataFrame(r['history'])
    axes[0].plot(hist['gen'], hist['rank_real'],
                 color=colors[i], alpha=0.8,
                 label=f'GA seed={r["seed"]}')

axes[0].axhline(int(rs_info.get('rank_real',0)), color='red',
                linestyle='--', label=f'RS rank={int(rs_info.get("rank_real",0))}')
axes[0].axhline(greedy_search(20)['rank_real'], color='gold',
                linestyle='--', linewidth=2,
                label=f'Greedy K=20 rank={greedy_search(20)["rank_real"]}')
axes[0].set_yscale('log')
axes[0].set_xlabel('Generación')
axes[0].set_ylabel('Rank real (log, menor=mejor)')
axes[0].set_title('Convergencia GA Nivel 2\nvs RS y Greedy')
axes[0].legend(fontsize=9)
axes[0].invert_yaxis()

# Acc_valid por generación
for i, r in enumerate(results_ga2):
    hist = pd.DataFrame(r['history'])
    axes[1].plot(hist['gen'], hist['acc_valid'],
                 color=colors[i], alpha=0.8,
                 label=f'GA seed={r["seed"]}')

axes[1].axhline(rs_info.get('acc_valid',0), color='red',
                linestyle='--', label='RS')
axes[1].axhline(greedy_search(20)['acc_valid'], color='gold',
                linestyle='--', linewidth=2, label='Greedy K=20')
axes[1].set_xlabel('Generación')
axes[1].set_ylabel('acc_valid real (%)')
axes[1].set_title('Accuracy real de la mejor arq.\npor generación')
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig(f'{SALIDAS}/ga_nivel2_convergencia.png', dpi=120, bbox_inches='tight')
plt.show()

"""## Bloque 7 — NSGA-II: búsqueda multi-objetivo (accuracy vs eficiencia)

Para búsqueda single-objective, greedy sobre el proxy es el baseline imbatible.
El GA tiene ventaja real cuando el objetivo es **encontrar un conjunto diverso**
de arquitecturas no dominadas en el espacio (accuracy, eficiencia).

**NSGA-II** mantiene un frente de Pareto de soluciones donde ninguna es mejor
en todos los objetivos simultáneamente. El usuario elige según su contexto:
- Deploy en móvil → priorizar params bajos
- Servidor → priorizar accuracy máxima

**Objetivos:**
- Maximizar: proxy_ga (estimador de accuracy)
- Minimizar: params_k (tamaño del modelo)

Comparamos el frente de Pareto del NSGA-II contra:
- RS multi-objetivo (mismo presupuesto)
- Frente de Pareto "real" (ground truth del benchmark completo)
"""

# ── NSGA-II ───────────────────────────────────────────────────

def dominates(a, b):
    """a domina a b si es mejor o igual en todos los obj y estrictamente mejor en uno."""
    return (a[0] >= b[0] and a[1] <= b[1] and
            (a[0] > b[0] or a[1] < b[1]))

def fast_non_dominated_sort(pop, scores):
    """Retorna lista de frentes [frente0, frente1, ...]."""
    n = len(pop)
    dominated_by = [0] * n
    dominates_list = [[] for _ in range(n)]
    fronts = [[]]

    for i in range(n):
        for j in range(n):
            if i == j: continue
            if dominates(scores[i], scores[j]):
                dominates_list[i].append(j)
            elif dominates(scores[j], scores[i]):
                dominated_by[i] += 1
        if dominated_by[i] == 0:
            fronts[0].append(i)

    k = 0
    while fronts[k]:
        next_front = []
        for i in fronts[k]:
            for j in dominates_list[i]:
                dominated_by[j] -= 1
                if dominated_by[j] == 0:
                    next_front.append(j)
        k += 1
        fronts.append(next_front)
    return fronts[:-1]

def crowding_distance(scores, front):
    if len(front) <= 2:
        return [np.inf] * len(front)
    dists = [0.0] * len(front)
    for obj in range(2):
        vals = [scores[i][obj] for i in front]
        order = np.argsort(vals)
        dists[order[0]] = dists[order[-1]] = np.inf
        v_range = vals[order[-1]] - vals[order[0]] + 1e-10
        for k in range(1, len(front)-1):
            dists[order[k]] += (vals[order[k+1]] - vals[order[k-1]]) / v_range
    return dists

def nsga2_select(pop, scores, pop_size):
    fronts = fast_non_dominated_sort(pop, scores)
    new_pop, new_scores = [], []
    for front in fronts:
        if len(new_pop) + len(front) <= pop_size:
            for i in front:
                new_pop.append(pop[i][:])
                new_scores.append(scores[i])
        else:
            cd = crowding_distance(scores, front)
            sorted_front = sorted(range(len(front)),
                                  key=lambda x: cd[x], reverse=True)
            needed = pop_size - len(new_pop)
            for idx in sorted_front[:needed]:
                new_pop.append(pop[front[idx]][:])
                new_scores.append(scores[front[idx]])
            break
    return new_pop, new_scores

def get_objectives(genes):
    """Retorna (proxy_score, params_k) para NSGA-II."""
    astr = genes_to_arch_str(genes)
    info = proxy_lookup.get(astr, {})
    proxy_s = info.get('proxy_ga', -np.inf)
    params  = info.get('params_k', np.inf)
    return (proxy_s, params)

def run_nsga2(pop_size=80, n_gen=40, p_mut=0.2,
              p_cross=0.8, seed=42):
    random.seed(seed); np.random.seed(seed)
    pop    = [random_ind() for _ in range(pop_size)]
    scores = [get_objectives(ind) for ind in pop]
    n_evals = pop_size
    history_fronts = []

    for gen in range(n_gen):
        # Reproducción
        offspring = []
        while len(offspring) < pop_size:
            fronts = fast_non_dominated_sort(pop, scores)
            ranks  = [0]*len(pop)
            for r, front in enumerate(fronts):
                for i in front: ranks[i] = r

            def nsga_tournament(k=2):
                cands = random.sample(range(len(pop)), k)
                c     = min(cands, key=lambda i: (
                    ranks[i],
                    -crowding_distance(scores, fronts[ranks[i]])[
                        fronts[ranks[i]].index(i)
                        if i in fronts[ranks[i]] else 0
                    ]
                ))
                return pop[c][:]

            p1, p2 = nsga_tournament(), nsga_tournament()
            c1, c2 = one_point_crossover(p1,p2) \
                     if random.random()<p_cross else (p1[:],p2[:])
            offspring.append(mutate(c1, p_mut))
            if len(offspring) < pop_size:
                offspring.append(mutate(c2, p_mut))
            n_evals += 1

        # Combinar padres + hijos y seleccionar
        combined_pop    = pop + offspring
        combined_scores = scores + [get_objectives(ind) for ind in offspring]
        pop, scores     = nsga2_select(combined_pop, combined_scores, pop_size)

        # Guardar frente actual
        fronts    = fast_non_dominated_sort(pop, scores)
        pf        = [(scores[i][0], scores[i][1]) for i in fronts[0]]
        history_fronts.append(pf)

    # Frente de Pareto final → lookup acc_valid real
    fronts    = fast_non_dominated_sort(pop, scores)
    pareto    = []
    for i in fronts[0]:
        astr = genes_to_arch_str(pop[i])
        info = proxy_lookup.get(astr, {})
        pareto.append({
            'arch_str' : astr,
            'proxy_ga' : scores[i][0],
            'params_k' : scores[i][1],
            'acc_valid': info.get('acc_valid', np.nan),
            'rank_real': info.get('rank_real', np.nan),
        })
    return pd.DataFrame(pareto), history_fronts, n_evals

# ── RS multi-objetivo (baseline) ─────────────────────────────
def rs_pareto(n_evals=3200, seed=42):
    random.seed(seed)
    candidates = []
    for _ in range(n_evals):
        ind  = random_ind()
        astr = genes_to_arch_str(ind)
        info = proxy_lookup.get(astr, {})
        candidates.append({
            'proxy_ga' : info.get('proxy_ga', -np.inf),
            'params_k' : info.get('params_k', np.inf),
            'acc_valid': info.get('acc_valid', np.nan),
            'rank_real': info.get('rank_real', np.nan),
        })
    df_rs = pd.DataFrame(candidates)
    # Frente de Pareto manual
    pareto = []
    for _, row in df_rs.iterrows():
        dominated = any(
            (r['proxy_ga'] >= row['proxy_ga'] and
             r['params_k'] <= row['params_k'] and
             (r['proxy_ga'] > row['proxy_ga'] or r['params_k'] < row['params_k']))
            for _, r in df_rs.iterrows()
        )
        if not dominated:
            pareto.append(row)
    return pd.DataFrame(pareto)

# ── Frente de Pareto real (ground truth) ─────────────────────
def real_pareto(df):
    pareto = []
    for _, row in df.iterrows():
        dominated = ((df['acc_valid'] >= row['acc_valid']) &
                     (df['params_k']  <= row['params_k']) &
                     ((df['acc_valid'] > row['acc_valid']) |
                      (df['params_k']  < row['params_k']))).any()
        if not dominated:
            pareto.append(row)
    return pd.DataFrame(pareto).sort_values('params_k')

# ── Ejecutar ──────────────────────────────────────────────────
print('Ejecutando NSGA-II (pop=80, gen=40)...')
df_pareto_nsga2, hist_fronts, n_ev_nsga2 = run_nsga2(
    pop_size=80, n_gen=40, seed=42
)
print(f'✓ NSGA-II: {len(df_pareto_nsga2)} soluciones en el frente  '
      f'({n_ev_nsga2} evals)')

print('\nComputando frente de Pareto RS...')
df_pareto_rs = rs_pareto(n_evals=n_ev_nsga2, seed=42)
print(f'✓ RS Pareto: {len(df_pareto_rs)} soluciones')

print('\nComputando frente de Pareto real (ground truth)...')
df_pareto_real = real_pareto(df_full)
print(f'✓ Pareto real: {len(df_pareto_real)} soluciones')

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# ── Frentes de Pareto comparados ──────────────────────────────
ax = axes[0]
ax.scatter(df_pareto_real['params_k'], df_pareto_real['acc_valid'],
           c='gold', s=40, zorder=3, label=f'Pareto real ({len(df_pareto_real)} arqs)',
           edgecolors='black', linewidths=0.5)
ax.plot(df_pareto_real.sort_values('params_k')['params_k'],
        df_pareto_real.sort_values('params_k')['acc_valid'],
        'gold', alpha=0.5, linewidth=1)

ax.scatter(df_pareto_nsga2['params_k'], df_pareto_nsga2['acc_valid'],
           c='steelblue', s=60, zorder=4,
           label=f'NSGA-II ({len(df_pareto_nsga2)} arqs)',
           edgecolors='black', linewidths=0.5)

ax.scatter(df_pareto_rs['params_k'], df_pareto_rs['acc_valid'],
           c='tomato', s=40, zorder=2, alpha=0.7,
           label=f'RS Pareto ({len(df_pareto_rs)} arqs)',
           marker='^')

ax.set_xlabel('Parámetros (K)')
ax.set_ylabel('acc_valid real (%)')
ax.set_title('Frentes de Pareto: NSGA-II vs RS vs Ground Truth')
ax.legend(fontsize=9)

# ── Convergencia del frente NSGA-II ──────────────────────────
ax2 = axes[1]
best_acc_by_gen = [max(p[0] for p in front) for front in hist_fronts]
front_size      = [len(front) for front in hist_fronts]

ax2.plot(best_acc_by_gen, color='steelblue',
         label='Mejor proxy en frente')
ax2b = ax2.twinx()
ax2b.plot(front_size, color='darkorange', linestyle='--',
          label='Tamaño del frente')
ax2.set_xlabel('Generación')
ax2.set_ylabel('Mejor proxy score', color='steelblue')
ax2b.set_ylabel('Soluciones en frente de Pareto', color='darkorange')
ax2.set_title('Convergencia NSGA-II')
lines1, labels1 = ax2.get_legend_handles_labels()
lines2, labels2 = ax2b.get_legend_handles_labels()
ax2.legend(lines1+lines2, labels1+labels2, fontsize=9)

plt.tight_layout()
plt.savefig(f'{SALIDAS}/nsga2_pareto.png', dpi=120, bbox_inches='tight')
plt.show()

# ── Tabla del frente NSGA-II ──────────────────────────────────
print('\n─── Frente de Pareto NSGA-II (ordenado por params_k) ───')
cols_show = ['arch_str','acc_valid','params_k','rank_real']
print(df_pareto_nsga2.sort_values('params_k')[cols_show]
      .to_string(index=False))

print(f'\n─── Comparación de calidad del frente ───────────────────')
print(f'  {"Método":15s}  {"Mejor acc":>10}  '
      f'{"Menor params":>13}  {"Soluciones":>11}')
print('  ' + '─'*54)
for nombre, df_p in [('NSGA-II', df_pareto_nsga2),
                      ('RS',      df_pareto_rs),
                      ('Real GT', df_pareto_real)]:
    print(f'  {nombre:15s}  '
          f'{df_p["acc_valid"].max():>10.4f}%  '
          f'{df_p["params_k"].min():>13.1f}K  '
          f'{len(df_p):>11}')

"""## Bloque 8 — Espacio extendido: recalibración y búsqueda

**Espacio extendido:** channel ∈ {8,16,32,64} × num_cells ∈ {3,5,7,9} × 5⁶ topologías
= 250.000 arquitecturas posibles, la mayoría fuera del benchmark.

**Estrategia de recalibración en 3 pasos:**
1. Muestrear ~50 arquitecturas por cada combinación (channel, num_cells) = 800 arqs
2. Computar ZCPs → actualizar norm_params para cubrir el espacio extendido
3. Re-optimizar pesos GA Nivel 1 usando benchmark (único con ground truth)
   pero con la nueva normalización → pesos válidos en el espacio extendido

**Al final:** NSGA-II busca en el espacio extendido y entrenamos las top-3 candidatas.
"""

import itertools

CHANNELS   = [8, 16, 32, 64]
NUM_CELLS  = [3, 5, 7, 9]
SAMPLE_PER_GROUP = 50
CSV_ZCP_EXT = os.path.join(BASE_DIR, 'nats_zcps_extended.csv')

def build_network_ext(arch_str, n_classes=10, C=16, num_cells=5):
    """TinyNetwork con C y num_cells variables."""
    class TinyNetExt(nn.Module):
        def __init__(self):
            super().__init__()
            self.stem    = nn.Sequential(
                nn.Conv2d(3, C, 3, padding=1, bias=False),
                nn.BatchNorm2d(C))
            # stride=2 en posiciones 1 y (num_cells//2 + 1) si hay reducción
            strides = []
            for i in range(num_cells):
                if num_cells <= 3:
                    strides.append(2 if i == 1 else 1)
                else:
                    strides.append(2 if i in [1, num_cells//2+1] else 1)
            self.cells      = nn.ModuleList(
                [NATSCell(arch_str, C, s) for s in strides])
            self.lastact    = nn.Sequential(
                nn.BatchNorm2d(C), nn.ReLU(inplace=False))
            self.gap        = nn.AdaptiveAvgPool2d(1)
            self.classifier = nn.Linear(C, n_classes)
        def forward(self, x):
            x = self.stem(x)
            for cell in self.cells: x = cell(x)
            x = self.lastact(x)
            x = self.gap(x).view(x.size(0), -1)
            return self.classifier(x), None
    return TinyNetExt().to(DEVICE)

def count_params_k(arch_str, C, num_cells):
    net = build_network_ext(arch_str, C=C, num_cells=num_cells)
    return sum(p.numel() for p in net.parameters()) / 1000

def compute_zcps_ext(arch_str, C, num_cells, x, y):
    try:
        net = build_network_ext(arch_str, C=C, num_cells=num_cells).train()
        torch.manual_seed(hash(arch_str + str(C) + str(num_cells)) % (2**31))
        for p in net.parameters():
            if p.dim() > 1: nn.init.kaiming_normal_(p)
        return {
            'grad_norm' : zcp_grad_norm(net, x, y),
            'snip'      : zcp_snip(net, x, y),
            'grasp'     : zcp_grasp(net, x, y),
            'jacob_cov' : zcp_jacob_cov(net, x),
            'synflow'   : zcp_synflow(net, x),
        }
    except Exception:
        return None

if os.path.exists(CSV_ZCP_EXT):
    df_ext = pd.read_csv(CSV_ZCP_EXT)
    print(f'✓ ZCPs extendidos cargados: {len(df_ext)} arquitecturas')
else:
    print('Computando ZCPs para espacio extendido...')
    print(f'  {len(CHANNELS)} canales × {len(NUM_CELLS)} celdas × '
          f'{SAMPLE_PER_GROUP} muestras = '
          f'{len(CHANNELS)*len(NUM_CELLS)*SAMPLE_PER_GROUP} arquitecturas\n')

    rows_ext = []
    np.random.seed(42)
    all_arch_strs = df['arch_str'].tolist()

    for C, nc in tqdm(list(itertools.product(CHANNELS, NUM_CELLS))):
        sample_archs = np.random.choice(all_arch_strs,
                                        size=SAMPLE_PER_GROUP,
                                        replace=False)
        for astr in sample_archs:
            res = compute_zcps_ext(astr, C, nc, x_batch, y_batch)
            if res:
                res['arch_str']  = astr
                res['channel']   = C
                res['num_cells'] = nc
                res['params_k']  = count_params_k(astr, C, nc)
                rows_ext.append(res)

    df_ext = pd.DataFrame(rows_ext)
    df_ext.to_csv(CSV_ZCP_EXT, index=False)
    print(f'✓ Guardado: {len(df_ext)} arquitecturas en {CSV_ZCP_EXT}')

print(f'\n─── Rangos de ZCPs en espacio extendido ─────────────────')
for col in ZCP_COLS:
    if col == 'params_k': continue
    print(f'  {col:12s}: [{df_ext[col].min():.3f}, {df_ext[col].max():.3f}]')
print(f'  {"params_k":12s}: [{df_ext["params_k"].min():.1f}K, '
      f'{df_ext["params_k"].max():.1f}K]')

# ── Combinar benchmark + extended para nueva normalización ───
df_combined_for_norm = pd.concat([
    df_full[ZCP_COLS],
    df_ext[ZCP_COLS]
], ignore_index=True)

print('─── Actualización de norm_params (espacio extendido) ────')
norm_params_ext = {}
for col in ZCP_COLS:
    r, _ = stats.spearmanr(df_full[col], df_full['acc_valid'])
    sign  = 1 if r >= 0 else -1
    vals  = df_combined_for_norm[col] * sign
    vmin, vmax = vals.min(), vals.max()
    norm_params_ext[col] = {'sign': sign, 'min': vmin, 'max': vmax}

    old_range = norm_params[col]['max'] - norm_params[col]['min']
    new_range = vmax - vmin
    print(f'  {col:12s}: rango {old_range:.2f} → {new_range:.2f}  '
          f'(factor {new_range/old_range:.2f}x)')

# ── Re-normalizar benchmark con nueva escala ─────────────────
df_full_renorm = df_full.copy()
for col in ZCP_COLS:
    sign = norm_params_ext[col]['sign']
    vmin = norm_params_ext[col]['min']
    vmax = norm_params_ext[col]['max']
    vals = df_full_renorm[col] * sign
    df_full_renorm[f'{col}_norm'] = np.clip(
        (vals - vmin) / (vmax - vmin + 1e-8), 0, 1
    )

# ── Re-calibrar conjunto de calibración ──────────────────────
df_calib_renorm = pd.read_csv(CSV_ZCP)[['arch_id']].merge(
    df_full_renorm, on='arch_id'
)

# ── Re-optimizar GA Nivel 1 con nueva normalización ──────────
def fitness_weights_renorm(w, k=50):
    return precision_at_k(weights_to_dict(w), df_calib_renorm, k=k)

print('\nRe-optimizando GA Nivel 1 con nueva normalización...')
results_ga1_ext = []
for run in range(10):
    random.seed(run * 17)
    pop  = [random_weights() for _ in range(20)]
    fits = [fitness_weights_renorm(ind) for ind in pop]

    for gen in range(5):
        sorted_idx = sorted(range(len(pop)),
                           key=lambda i: fits[i], reverse=True)
        new_pop = [pop[i][:] for i in sorted_idx[:2]]
        while len(new_pop) < 20:
            p1 = tournament(pop, fits)
            p2 = tournament(pop, fits)
            c  = blx_crossover(p1, p2) if random.random()<0.8 else p1[:]
            if random.random() < 0.3:
                c = mutate_gaussian(c, 0.15)
            new_pop.append(c)
        pop  = new_pop
        fits = [fitness_weights_renorm(ind) for ind in pop]

    best_idx = max(range(len(pop)), key=lambda i: fits[i])
    results_ga1_ext.append({
        'best_p50': fits[best_idx],
        'weights' : pop[best_idx]
    })

best_run_ext    = max(results_ga1_ext, key=lambda r: r['best_p50'])
best_weights_ext = weights_to_dict(best_run_ext['weights'])

print(f'\n✓ P@50 con nueva normalización:')
print(f'  Media : {np.mean([r["best_p50"] for r in results_ga1_ext]):.4f}')
print(f'  Mejor : {best_run_ext["best_p50"]:.4f}')
print(f'\n─── Pesos recalibrados ──────────────────────────────────')
for col, w in best_weights_ext.items():
    bar = '█' * int(abs(w) * 20)
    print(f'  {col:12s}: {w:+.4f}  {"+" if w>=0 else "-"}{bar}')

# ── Fitness para arquitecturas del espacio extendido ─────────
def compute_fitness_ext(arch_str, C, num_cells):
    """
    Computa ZCPs, normaliza con norm_params_ext,
    aplica pesos recalibrados → score del proxy.
    """
    res = compute_zcps_ext(arch_str, C, num_cells, x_batch, y_batch)
    if res is None:
        return -np.inf, np.inf

    score = 0.0
    for col in ZCP_COLS:
        if col == 'params_k': continue
        val      = res[col] * norm_params_ext[col]['sign']
        val_norm = np.clip(
            (val - norm_params_ext[col]['min']) /
            (norm_params_ext[col]['max'] - norm_params_ext[col]['min'] + 1e-8),
            0, 1
        )
        score += best_weights_ext[col] * val_norm

    # params_k real de la red construida
    params = count_params_k(arch_str, C, num_cells)
    p_norm = np.clip(
        (params * norm_params_ext['params_k']['sign']
         - norm_params_ext['params_k']['min']) /
        (norm_params_ext['params_k']['max']
         - norm_params_ext['params_k']['min'] + 1e-8),
        0, 1
    )
    score += best_weights_ext['params_k'] * p_norm
    return score, params

# ── Test en 3 arquitecturas de distintos tamaños ─────────────
print('─── Test de fitness en espacio extendido ────────────────')
print(f'  {"arch_str":50s}  {"C":>4}  {"nc":>4}  {"score":>8}  {"params":>8}')
print('  ' + '─'*78)
test_astr = df['arch_str'].iloc[1000]
for C, nc in [(8,3), (16,5), (32,7), (64,9)]:
    score, params = compute_fitness_ext(test_astr, C, nc)
    print(f'  {test_astr[:48]:50s}  {C:>4}  {nc:>4}  '
          f'{score:>8.4f}  {params:>6.1f}K')

# ── Cromosoma extendido: 8 genes ──────────────────────────────
# genes[0..5] → operaciones (0-4)
# genes[6]    → índice de channel {0:8, 1:16, 2:32, 3:64}
# genes[7]    → índice de num_cells {0:3, 1:5, 2:7, 3:9}

def decode_ext(genes):
    arch_str = genes_to_arch_str(genes[:6])
    C        = CHANNELS[genes[6]]
    nc       = NUM_CELLS[genes[7]]
    return arch_str, C, nc

def random_ind_ext():
    return ([random.randint(0,4) for _ in range(6)] +
            [random.randint(0,3), random.randint(0,3)])

# Cache para evitar recomputar ZCPs
fitness_cache_ext = {}

def get_objectives_ext(genes):
    key = tuple(genes)
    if key not in fitness_cache_ext:
        astr, C, nc = decode_ext(genes)
        score, params = compute_fitness_ext(astr, C, nc)
        fitness_cache_ext[key] = (score, params)
    return fitness_cache_ext[key]

def mutate_ext(ind, p_mut=0.15):
    new = ind[:]
    for i in range(6):
        if random.random() < p_mut:
            new[i] = random.randint(0, 4)
    if random.random() < p_mut: new[6] = random.randint(0, 3)
    if random.random() < p_mut: new[7] = random.randint(0, 3)
    return new

def crossover_ext(p1, p2):
    pt = random.randint(1, 7)
    return p1[:pt]+p2[pt:], p2[:pt]+p1[pt:]

print('Ejecutando NSGA-II en espacio extendido...')
print('(pop=60, gen=30, ~1800+ evaluaciones de proxy)\n')

random.seed(42)
pop_ext  = [random_ind_ext() for _ in range(60)]
scores_ext = [get_objectives_ext(ind) for ind in pop_ext]
n_evals_ext = 60

for gen in tqdm(range(30)):
    offspring = []
    while len(offspring) < 60:
        fronts = fast_non_dominated_sort(pop_ext, scores_ext)
        ranks  = [0]*len(pop_ext)
        for r, front in enumerate(fronts):
            for i in front: ranks[i] = r
        def sel(k=2):
            cands = random.sample(range(len(pop_ext)), k)
            return pop_ext[min(cands, key=lambda i: ranks[i])][:]
        p1, p2 = sel(), sel()
        c1, c2 = crossover_ext(p1,p2) \
                 if random.random()<0.8 else (p1[:],p2[:])
        offspring.append(mutate_ext(c1))
        if len(offspring) < 60: offspring.append(mutate_ext(c2))

    new_scores = [get_objectives_ext(ind) for ind in offspring]
    n_evals_ext += sum(1 for ind in offspring
                       if tuple(ind) not in fitness_cache_ext)

    combined_pop    = pop_ext + offspring
    combined_scores = scores_ext + new_scores
    pop_ext, scores_ext = nsga2_select(combined_pop,
                                        combined_scores, 60)

print(f'\n✓ NSGA-II extendido: {n_evals_ext} evaluaciones únicas')

# ── Frente de Pareto final ────────────────────────────────────
fronts_ext  = fast_non_dominated_sort(pop_ext, scores_ext)
pareto_ext  = []
seen        = set()
for i in fronts_ext[0]:
    key = tuple(pop_ext[i])
    if key in seen: continue
    seen.add(key)
    astr, C, nc = decode_ext(pop_ext[i])
    score, params = scores_ext[i]
    # Verificar si está en el benchmark
    match = df[df['arch_str'] == astr]
    acc_bench = float(match['acc_valid'].values[0]) \
                if (len(match) > 0 and C==16 and nc==5) else None
    pareto_ext.append({
        'arch_str' : astr,
        'channel'  : C,
        'num_cells': nc,
        'proxy_score': score,
        'params_k' : params,
        'acc_bench': acc_bench,
        'in_benchmark': (len(match)>0 and C==16 and nc==5),
    })

df_pareto_ext = pd.DataFrame(pareto_ext).sort_values('params_k')

print(f'\n─── Frente de Pareto extendido ({len(df_pareto_ext)} soluciones únicas) ───')
cols_show = ['channel','num_cells','params_k','proxy_score',
             'acc_bench','in_benchmark','arch_str']
print(df_pareto_ext[cols_show].to_string(index=False))

# ── Top-5 candidatas para entrenar ───────────────────────────
print('\n─── Top-5 candidatas por proxy_score ───────────────────')
top5 = df_pareto_ext.nlargest(5, 'proxy_score')[cols_show]
print(top5.to_string(index=False))

"""## Bloque 9 — Entrenamiento y validación real

Entrenamos las top-5 candidatas del frente de Pareto extendido.
Para comparación justa con el benchmark:
- Mismo dataset: CIFAR-10
- Misma configuración: SGD, lr=0.025, cosine decay, 200 épocas
- Mismo criterio: acc_valid final

**Referencia:** mejor arquitectura del benchmark = 91.68% (channel=16, nc=5)

**Estrategia de 2 fases:**
1. Entrenar todas con 50 épocas → filtrar las 2 mejores
2. Entrenar las 2 mejores con 200 épocas completas → resultado final
"""

import torch
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
import torchvision.transforms as T
import torchvision

# ── Dataset CIFAR-10 completo con augmentación ────────────────
transform_train = T.Compose([
    T.RandomCrop(32, padding=4),
    T.RandomHorizontalFlip(),
    T.ToTensor(),
    T.Normalize((0.4914,0.4822,0.4465),(0.2470,0.2435,0.2616)),
])
transform_test = T.Compose([
    T.ToTensor(),
    T.Normalize((0.4914,0.4822,0.4465),(0.2470,0.2435,0.2616)),
])

train_set  = torchvision.datasets.CIFAR10(CIFAR_DIR, train=True,
                                           download=True,
                                           transform=transform_train)
val_set    = torchvision.datasets.CIFAR10(CIFAR_DIR, train=False,
                                           download=True,
                                           transform=transform_test)

train_loader = torch.utils.data.DataLoader(
    train_set, batch_size=96, shuffle=True,
    num_workers=0, pin_memory=True)
val_loader   = torch.utils.data.DataLoader(
    val_set, batch_size=256, shuffle=False,
    num_workers=0, pin_memory=True)

def train_network(arch_str, C, num_cells, n_epochs=50, lr=0.025):
    """Entrena una TinyNetExt y retorna acc_valid por época."""
    net       = build_network_ext(arch_str, C=C, num_cells=num_cells)
    optimizer = optim.SGD(net.parameters(), lr=lr,
                          momentum=0.9, weight_decay=3e-4)
    scheduler = CosineAnnealingLR(optimizer, T_max=n_epochs)
    criterion = nn.CrossEntropyLoss()

    history = []
    for epoch in range(n_epochs):
        # ── Train ─────────────────────────────────────────────
        net.train()
        for xb, yb in train_loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            optimizer.zero_grad()
            out, _ = net(xb)
            criterion(out, yb).backward()
            optimizer.step()
        scheduler.step()

        # ── Validate ──────────────────────────────────────────
        net.eval()
        correct = total = 0
        with torch.no_grad():
            for xb, yb in val_loader:
                xb, yb = xb.to(DEVICE), yb.to(DEVICE)
                preds   = net(xb)[0].argmax(1)
                correct += (preds == yb).sum().item()
                total   += yb.size(0)
        acc = 100 * correct / total
        history.append(acc)

        if (epoch+1) % 10 == 0:
            print(f'    ep {epoch+1:3d}/{n_epochs}: acc={acc:.2f}%')

    return max(history), history, net

# ── Fase 1: entrenar top-2 por 50 épocas ─────────────────────
print('═'*60)
print('FASE 1: Top-2 candidatas × 50 épocas')
print('═'*60)

top2_candidates = df_pareto_ext.nlargest(2, 'proxy_score')
phase1_results  = []

for _, row in top2_candidates.iterrows():
    astr = row['arch_str']
    C    = int(row['channel'])
    nc   = int(row['num_cells'])
    p    = row['params_k']
    print(f'\n▶ channel={C}, nc={nc}, params={p:.1f}K')
    print(f'  {astr}')
    best_acc, hist, _ = train_network(astr, C, nc, n_epochs=50)
    phase1_results.append({
        'arch_str' : astr, 'channel': C, 'num_cells': nc,
        'params_k' : p,    'proxy'  : row['proxy_score'],
        'acc_50ep' : best_acc, 'history': hist,
    })
    print(f'  → Mejor acc (50 ep): {best_acc:.4f}%')

phase1_df = pd.DataFrame(phase1_results).drop(columns=['history'])
print('\n─── Resumen Fase 1 ──────────────────────────────────────')
print(phase1_df[['channel','num_cells','params_k',
                 'proxy','acc_50ep']].to_string(index=False))

# ── Fase 2: la mejor por 100 épocas ─────────────────────────────
print('\n' + '═'*60)
print('FASE 2: La mejor por acc_50ep × 100 épocas completas')
print('═'*60)
BENCHMARK_BEST = 91.68   # referencia

top1 = sorted(phase1_results, key=lambda r: r['acc_50ep'], reverse=True)[:1]
final_results = []

for r in top1:
    astr = r['arch_str']
    C, nc = r['channel'], r['num_cells']
    print(f'\n▶ channel={C}, nc={nc}, params={r["params_k"]:.1f}K')
    best_acc, hist, net = train_network(astr, C, nc, n_epochs=100)
    final_results.append({**r, 'acc_100ep': best_acc, 'history_100': hist})
    print(f'  → Mejor acc (100 ep): {best_acc:.4f}%')
    print(f'  → Benchmark best    : {BENCHMARK_BEST:.4f}%')
    delta = best_acc - BENCHMARK_BEST
    symbol = '✓ SUPERA' if delta > 0 else '✗ No supera'
    print(f'  → Diferencia: {delta:+.4f}%  {symbol}')

# ── Guardar modelos y resultados ──────────────────────────────
os.makedirs(f'{SALIDAS}/modelos', exist_ok=True)
for r in final_results:
    fname = (f'{SALIDAS}/modelos/'
             f'C{r["channel"]}_nc{r["num_cells"]}_'
             f'acc{r["acc_100ep"]:.2f}.pt')
    # Solo guardamos los resultados, no el modelo completo
    torch.save({'arch_str': r['arch_str'],
                'channel' : r['channel'],
                'num_cells': r['num_cells'],
                'acc_100ep': r['acc_100ep'],
                'history_100': r['history_100']}, fname)
    print(f'✓ Guardado: {fname}')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Curvas de entrenamiento (100 ep) ─────────────────────────
colors = ['steelblue', 'darkorange']
for i, r in enumerate(final_results):
    axes[0].plot(r['history_100'], color=colors[i], linewidth=2,
                 label=f'C={r["channel"]}, nc={r["num_cells"]}, '
                       f'{r["params_k"]:.0f}K params')
axes[0].axhline(BENCHMARK_BEST, color='red', linestyle='--',
                linewidth=2, label=f'Benchmark best ({BENCHMARK_BEST}%)')
axes[0].set_xlabel('Época')
axes[0].set_ylabel('Accuracy (%)')
axes[0].set_title('Entrenamiento arquitecturas extendidas vs benchmark')
axes[0].legend(fontsize=9)

# ── Frente de Pareto final con resultados reales ─────────────
axes[1].scatter(df_pareto_ext['params_k'],
                df_pareto_ext['proxy_score'],
                c='steelblue', s=50, alpha=0.7,
                label='Frente Pareto extendido (proxy)')
for r in final_results:
    axes[1].scatter(r['params_k'], r['proxy'],
                    c='gold', s=200, zorder=5,
                    edgecolors='black', linewidths=2)
    axes[1].annotate(f'{r["acc_100ep"]:.2f}%',
                     (r['params_k'], r['proxy']),
                     textcoords='offset points',
                     xytext=(5,5), fontsize=9, color='red', fontweight='bold')
axes[1].set_xlabel('Parámetros (K)')
axes[1].set_ylabel('Proxy score')
axes[1].set_title('Frente de Pareto extendido\n(oro = entrenadas, etiqueta = acc real)')
axes[1].legend(fontsize=9)

plt.tight_layout()
plt.savefig(f'{SALIDAS}/resultados_finales.png', dpi=120, bbox_inches='tight')
plt.show()

# ── Tabla resumen completa del proyecto ───────────────────────
print('\n' + '═'*70)
print('TABLA RESUMEN COMPLETA DEL PROYECTO')
print('═'*70)
print(f'  {"Método":30s}  {"acc_valid":>10}  {"rank":>8}  {"params_k":>10}')
print('  ' + '─'*60)
print(f'  {"Benchmark best (ground truth)":30s}  '
      f'{"91.68%":>10}  {"1":>8}  {"615K":>10}')
print(f'  {"GA N1+Greedy K=20":30s}  '
      f'{"91.50%":>10}  {"7":>8}  {"?":>10}')
print(f'  {"GA N1+GA N2":30s}  '
      f'{"90.30%":>10}  {"628":>8}  {"1531K":>10}')
print(f'  {"NSGA-II benchmark":30s}  '
      f'{"90.30%":>10}  {"628":>8}  {"1531K":>10}')
for r in final_results:
    vs = '✓' if r['acc_100ep'] > BENCHMARK_BEST else '✗'
    print(f'  {"NSGA-II ext C="+str(r["channel"])+" nc="+str(r["num_cells"]):30s}  '
          f'{r["acc_100ep"]:>9.2f}%  '
          f'{"N/A":>8}  '
          f'{r["params_k"]:>8.0f}K  {vs}')
print('═'*70)